{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-lightsail-sd.serviceAccountName" . }}
  labels:
{{ include "prometheus-lightsail-sd.labels" . | nindent 4 }}
{{- end -}}
